AllStarLink/ASL3-Manual

docs/adv-topics/sip-phone.md
I updated sip-phone.md to remove color name references.  This was in the original google.doc.
The color references were replaced with the actual text.
This closes #9
=> Update sip-phone.md for color references

mkdocs.yml
The `nmcli` commands at the bottom of the cockpit-network page were being smashed into one line, creating confusion on the correct command to use.
The original markdown spec doesn't render multiline code blocks. We need the superfences plugin in order for it to render correctly. 
Closes https://github.com/AllStarLink/ASL3/issues/84
=> need superfences to render multiline code blocks correctly

docs/adv-topics/sip-phone.md
PTT/VOX, say connected file path, and remove announcement text updated in sip-phone.  Reference to orange text removed as the text does not show up orange for the removal of announcement when connecting.  The file path for the connected message in extensions.conf was missing the rpt/, added it.  No discussion of *99/# for PTT on SIP phones or the alternate VOX method, added that text.
=> PTT/VOX and other updates to sip-phone topic

docs/adv-topics/allowdenylists.md
I noticed today that the example for adding nodes to the allow/deny lists isn't working.  The note at the end does not appear to be allowed, and items are separated by space not '/' in the database command: 
allstar-3*CLI> database put
Usage: database put <family> <key> <value>
Adds or updates an entry in the Asterisk database for
a given family, key, and value.
=> Allow/Deny Update

docs/adv-topics/autopatch.md
Major step up in autopatch documentation.  Added Mason's github info on voip.ms IAX setup and my own flowroute SIP setup info.  Other updates include duplex info.
=> autopatch updates with IAX/SIP notes

docs/allmon3/config.md
Existing configuration is incorrect for adding a VOTER site. This corrects the example and adds additional context/examples since adding a VOTER site does not make it show up automatically, and menu.ini needs to be created to make it populate in Allmon3.
=> Update Allmon3 configuration when adding VOTER sites.

README.md
Adding a more detailed process for setting up a WSL/Windows/VS Code environment for working with the manual.
Uses a WSL Linux distro on the local machine for all the Git related stuff, for those of us more used to working in a CLI, but also combines running VS Code on the Windows host for real-time editing/previewing changes.
Those more familiar with VS Code can probably do all the Git tasks through its interface... but that will be an exercise left to the user. :)
=> Adding instructions on building a Windows/WSL development environment

docs/adv-topics/daq.md, mkdocs.yml
Moved the DAQ-related config items out of the `rpt.conf` documentation, as it is orphaned code, and not applicable to most users.
Documenting it for future development.
=> Add documentation on the mysterious DAQ feature.

docs/config/config-structure.md, docs/config/rpt_conf.md, mkdocs.yml
Convert the page from the wiki to manual format.
Clean up, correct and add missing options. 
Remove remote base and DAQ information (to be documented elsewhere).
=> Convert rpt.conf from the wiki to the ASL3 Manual. 

docs/adv-topics/index.md, mkdocs.yml
Added an `index.md` landing page for the Advanced Topics section.
Re-organized the Table of Contents to alphabetize the sections, except for New Commands and Incompatibilities, which should be the first sections to review, before getting into anything else.
=> Add index.md page for the Advanced Topics section, re-org ToC.

docs/developers/index.md, mkdocs.yml
Adding an `index.md` landing page for the Developer section of the manual.
=> Create an index.md for the Developer section of the manual.

docs/mans/index.md, mkdocs.yml
Adding an `index.md` landing page for the Manual Pages section.
=> Add index.md for the Mans section of the manual

docs/config/index.md, docs/config/rpt_conf.md, mkdocs.yml
Add an `index.md` landing page for the Config Files section of the manual.
=> Add index.md for Config Files section.

docs/adv-topics/macros.md, docs/config/rpt_conf.md, mkdocs.yml
Clean up and convert the Macro Use and Format Wiki page for inclusion in the ASL3 manual.
=> Convert Macro Use and Format Wiki page for ASL3 manual

docs/adv-topics/eurorptr.md, docs/config/rpt_conf.md, mkdocs.yml
Clean up and convert the European Repeater Operation Wiki page for inclusion in the ASL3 manual.
=> Convert Euro Repeater Wiki page for ASL3 manual

docs/adv-topics/permanentnode.md, mkdocs.yml
Clean up and convert the Permanent Node Connections Wiki page for inclusion in the ASL3 manual.
=> Convert Permanent Node Wiki page for ASL3 manual.

docs/adv-topics/commands.md
Fixed a spelling error on the Menu page that subsequently broke a couple of anchor links on another page.
=> Fix a couple broken links, after fixing a previous typo.

docs/adv-topics/condiscpgm.md, docs/config/rpt_conf.md, mkdocs.yml
Clean up the formatting for `connpgm` and `discpgm` in `rpt.conf`, an create an Advanced Topics page for them with a simple example from the Community.
Closes #47
=> Add further documentation about connpgm and discpgm.

docs/adv-topics/mdc1200.md, docs/config/rpt_conf.md
Document the currently "un-documented" `mdclog` option in `rpt.conf`.
=> Document mdclog option in rpt.conf.

mkdocs.yml
When scrolling down long pages (`rpt.conf`), the top nav bar disappears. This makes it cumbersome to flip between manual sections. Sticky navigation tabs resolves this so that the nav bar is always present (in full-window mode).
=> Make top nav bar "stick" so it is always visible when scrolling.

docs/adv-topics/telemetry.md, docs/config/rpt_conf.md, mkdocs.yml
Trying to consolidate and update all the telemetry information.
Leaving most of the setting-related information in `rpt.conf` so that it isn't duplicated on the Telemetry Messages page.
Closes #87
=> Convert Telemetry Wiki page and update ASL3 telemetry docs.

docs/adv-topics/mdc1200.md, docs/config/rpt_conf.md
Documents the currently "un-documented" `dtmfkey` option and associated `dtmfkeys` stanza.
Also documents the special application leveraging these options to control node access via MDC-1200 per https://community.allstarlink.org/t/dtmfkey-and-or-mdc-for-ptt-id-bug/23238/3
=> Document dtmfkey/dtmfkeys and associated MDC-1200 access.

docs/config/simpleusb_conf.md, mkdocs.yml
Documenting all the `simpleusb.conf` options.
=> Document simpleusb.conf.

docs/adv-topics/gpio.md, docs/config/rpt_conf.md
`iobase` was missing from `rpt.conf`. It appears to actually only be used with Remote Bases, not when used for GPIO.
When using the parallel port for GPIO with a channel driver, as soon as one pin is defined, the parallel port will be activated (found some bugs with that, but that will be addressed later). 
In addition, SimpleUSB and USBRadio accept `pbase` and `pport` options in their `[general]` stanzas to override the base address and device. Those will be documented on the relevant `.conf` pages in the manual.
=> Move iobase to rpt.conf. Revise GPIO page regarding parallel port config.

docs/adv-topics/courtesytones.md, docs/config/rpt_conf.md
RANGER support code is removed from app_rpt; now remove manual references.
=> Remove references to RANGER courtesy tone and commands
