AllStarLink/ASL3-Manual

docs/adv-topics/autopatch.md
docs/adv-topics/index.md

This adds the advanced topic Autopatch.

Added advanced topic Autopatch

---

docs/adv-topics/index.md
docs/adv-topics/noderesolution.md
mkdocs.yml

This adds a Node Resolution topic to the advanced section.

Add Node Resolution advanced topic

---

docs/adv-topics/autopatch.md
docs/adv-topics/sip-phone.md

Added module loading info and clairfied SIP info in autopatch.md.  Added text to sip-phone.md to put module loading above [global] stanza in modules.conf, same in autopatch.md

SIP and Autopatch doc updates

---

.gitignore

This updates .gitignore to add the directory .vs/
We already include .vscode/ for vscode. I am adding .vs/ for visual studio.

Update .gitignore to add .vs/

---

docs/adv-topics/usbinterfaces.md
mkdocs.yml

This updates usbinterfaces.md for changes to res_usbradio.conf.  A new section for "Supported C-Media Chips" was added.

Update docs for res_usbradio.conf changes

---

docs/adv-topics/rxtoneburst.md
mkdocs.yml

Convert wiki page for ASL manual.

Convert and add documentation for RX Toneburst.

---

docs/adv-topics/litz.md
mkdocs.yml

Converting the LiTZ wiki page to put in the ASL3 manual.

Convert the LiTZ wiki page..

---

docs/adv-topics/dns-servers.md
docs/adv-topics/noderesolution.md
mkdocs.yml

I'll note that nodes.allstartlink.org does not resolve... should this be something else?

Convert DNS Servers Wiki page.

---

docs/mans/allmon3-passwd.md
mkdocs.yml

Converted man page from source repository.

Add allmon3-passwd man page.

---

docs/adv-topics/remotebase.md

Add the missing remote 61-64 mode change commands, as advised by W2DB.

Add missing mode change remote commands

---

docs/adv-topics/sleepmode.md
docs/config/rpt_conf.md
mkdocs.yml

Consolidate and clean up Sleep Mode documentation.

Convert documentation for Sleep Mode from Wiki to ASL3 manual.

---

docs/config/iax_conf.md
mkdocs.yml

Documenting the stanzas in iax.conf.

Adding iax.conf documentation.

---

docs/adv-topics/dtmffunctions.md
mkdocs.yml

Convert Wiki DTMF Functions page for ASL3 manual.

---

docs/adv-topics/tonesignalling.md
mkdocs.yml

Convert Wiki Tone Signalling page for ASL3 Manual.

---

docs/developers/versioning.md
mkdocs.yml

Add a manual page explaining package versioning.

---

docs/adv-topics/tonemacros.md
mkdocs.yml

Convert Wiki Tonemacro page for ASL3 Manual.

---

docs/basics/gettingstarted.md

Update the Getting Started page with Node Registration info.

---

docs/adv-topics/archivedir.md
docs/config/rpt_conf.md
mkdocs.yml

Convert the Wiki Archivedir page for the ASL3 manual.

---

docs/adv-topics/linkacttimer.md
docs/config/rpt_conf.md
mkdocs.yml

Convert Link Activity Timer Wiki page for ASL3 manual.

---

docs/user-guide/troubleshooting.md

Add further troubleshooting tips from the Wiki Troubleshooting page.

---

docs/config/rpt_conf.md

One of the previously "un-documented" `rpt.conf` settings.

Document the mdcmacro stanza.

---

docs/adv-topics/simplevoter.md
docs/config/rpt_conf.md
mkdocs.yml

Convert Simple Voter Wiki page for ASL3 manual.

---

docs/adv-topics/eventmgmt.md
docs/config/rpt_conf.md
mkdocs.yml

Convert Event Management Wiki page for ASL3 manual.

---

docs/adv-topics/eventmgmt.md
docs/adv-topics/gpio.md
docs/adv-topics/mdc1200.md
docs/adv-topics/simplevoter.md
docs/adv-topics/telemetry.md
docs/config/rpt_conf.md
mkdocs.yml

Convert Manipulating GPIO Wiki page for ASL3 manual.

---

docs/mans/asl-backup-menu.md
mkdocs.yml

Documenting the `asl-backup-menu` utility.

Create manual page for asl-backup-menu.

---

docs/adv-topics/dtmftoscript.md
mkdocs.yml

Convert Wiki page Passing DTMF to Shell Scripts for ASL3 Manual.

---

docs/adv-topics/scheduler.md
docs/config/rpt_conf.md
mkdocs.yml

Convert Scheduler Wiki page for ASl3 Manual.

---

docs/mans/asl-find-sound.md
docs/mans/asl-node-lookup.md
docs/mans/asl-play-arn.md
docs/mans/asl-say.md
docs/mans/asl-setup-dkms-mok.md

Updating formatting to use `code` blocks, instead of escaping chars. Editing for consistency.

Update formatting of manual pages for consistency.
